<ul class="list-group list-group-flush bg-transparent">
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> HTML 5</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> CSS 3</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> JavaScript</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> jQuery</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> PHP CORE OOP <a href="https://github.com/HasanaghaAzad/laravel-resume" target="_blank" class="position-absolute top-50  start-100 translate-middle badge rounded-pill bg-black">proof</a></li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> MVC</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> MySQL</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> SMTP / POP3/ FTP</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i> MSSQL</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> Bootstrap 3/4/5</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i> Laravel <a href="https://github.com/HasanaghaAzad/laravel-resume" target="_blank" class="position-absolute top-50  start-100 translate-middle badge rounded-pill bg-black">proof</a></li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i> Machine Learning</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> Apache</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i> Nginx</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i> Python</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> React</li>
       <li class="list-group-item bg-transparent text-light border-0">
              <i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> Node.js</li>
       <li class="list-group-item bg-transparent text-light border-0">
              <i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> Express
       </li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> Jasmine</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> MongoDB</li>
       <li class="list-group-item bg-transparent text-light border-0"><i class="bi bi-circle-fill"></i><i class="bi bi-circle-fill"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i><i class="bi bi-circle"></i> Redis</li>
</ul>